datadog_api_key: "{{ dd_api_key }}"
datadog_site: "{{ dd_api_url }}"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Application Check
        url: "http://localhost:{{ expose_port }}"
        timeout: 5
        method: GET
