datadog_api_key: "{{ datadog_api_key }}"
datadog_site: "{{ datadog_api_url }}"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Application Check
        url: http://localhost:80
        timeout: 5
        method: GET
