---

- hosts: webservers
  gather_facts: no
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started

  roles:
    - role: geerlingguy.pip
      become: yes
      tags: pip

    - role: datadog.datadog
      tags: datadog

  tasks:
    - name: Start Wiki Application
      community.docker.docker_container:
        name: app
        image: requarks/wiki:2.5
        restart_policy: always
        state: started
        ports:
          - 80:3000
        env:
          DB_TYPE: "{{ wiki_db_type }}"
          DB_HOST: "{{ wiki_db_host }}"
          DB_PORT: "{{ pstg_db_port | string }}"
          DB_USER: "{{ pstg_db_username }}"
          DB_PASS: "{{ pstg_db_password }}"
          DB_NAME: "{{ pstg_db_identifier }}"
