---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Include encrypted variables
      include_vars:
        file: ../group_vars/webservers/secret_vars_vault.yml
        name: secret

    - name: Generate Terraform variable file from template
      template:
        src: ../templates/secret.auto.tfvars.j2
        dest: ../../terraform/secret.auto.tfvars
