all:
  children:
    webservers:
      vars:
        ansible_ssh_user: ubuntu
      hosts:
        WebServer1:
          ansible_host: 35.88.237.47
        WebServer2:
          ansible_host: 18.236.155.139
