---

all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: ec2-35-91-150-155.us-west-2.compute.amazonaws.com
#      vars:
#        ansible_user: "{{ ansible_ssh_user }}"
#        ansible_ssh_private_key_file: "{{ private_key_file }}"
